import type { NewsCategory, NewsSourceInfo } from "./types";

export const NEWS_CATEGORIES: NewsCategory[] = [
  "Semua",
  "Pemerintahan",
  "Hukum & Korupsi",
  "Ekonomi & Kebijakan",
  "Nasional",
];

export const NEWS_SOURCES: NewsSourceInfo[] = [
  {
    id: "antara-politik",
    name: "ANTARA News",
    domain: "antaranews.com",
    url: "https://www.antaranews.com/rss/politik.xml",
    category: "Pemerintahan",
    color: "#005a9c",
    badge: "ANTARA",
    description: "Kantor Berita Nasional Indonesia - Berita Politik & Pemerintahan",
  },
  {
    id: "antara-hukum",
    name: "ANTARA News",
    domain: "antaranews.com",
    url: "https://www.antaranews.com/rss/hukum.xml",
    category: "Hukum & Korupsi",
    color: "#005a9c",
    badge: "ANTARA",
    description: "Kantor Berita Nasional Indonesia - Berita Hukum, Hankam & Peradilan",
  },
  {
    id: "antara-ekonomi",
    name: "ANTARA News",
    domain: "antaranews.com",
    url: "https://www.antaranews.com/rss/ekonomi.xml",
    category: "Ekonomi & Kebijakan",
    color: "#005a9c",
    badge: "ANTARA",
    description: "Kantor Berita Nasional Indonesia - Berita Ekonomi, Fiskal & Moneter",
  },
  {
    id: "cnn-nasional",
    name: "CNN Indonesia",
    domain: "cnnindonesia.com",
    url: "https://www.cnnindonesia.com/nasional/rss",
    category: "Nasional",
    color: "#cc0000",
    badge: "CNN ID",
    description: "CNN Indonesia - Berita Terkini Nasional & Isu Publik",
  },
  {
    id: "cnn-ekonomi",
    name: "CNN Indonesia",
    domain: "cnnindonesia.com",
    url: "https://www.cnnindonesia.com/ekonomi/rss",
    category: "Ekonomi & Kebijakan",
    color: "#cc0000",
    badge: "CNN ID",
    description: "CNN Indonesia - Berita Ekonomi, Bisnis & Regulasi",
  },
  {
    id: "cnbc-news",
    name: "CNBC Indonesia",
    domain: "cnbcindonesia.com",
    url: "https://www.cnbcindonesia.com/news/rss",
    category: "Pemerintahan",
    color: "#002d62",
    badge: "CNBC",
    description: "CNBC Indonesia - Berita Kebijakan, Pemerintahan & Makro",
  },
  {
    id: "cnbc-market",
    name: "CNBC Indonesia",
    domain: "cnbcindonesia.com",
    url: "https://www.cnbcindonesia.com/market/rss",
    category: "Ekonomi & Kebijakan",
    color: "#002d62",
    badge: "CNBC",
    description: "CNBC Indonesia - Pasar Modal, Industri & Kebijakan Ekonomi",
  },
  {
    id: "tempo-nasional",
    name: "Tempo.co",
    domain: "tempo.co",
    url: "https://rss.tempo.co/nasional",
    category: "Nasional",
    color: "#8a0000",
    badge: "TEMPO",
    description: "Tempo.co - Investigasi & Liputan Mendalam Nasional",
  },
  {
    id: "tempo-hukum",
    name: "Tempo.co",
    domain: "tempo.co",
    url: "https://rss.tempo.co/hukum",
    category: "Hukum & Korupsi",
    color: "#8a0000",
    badge: "TEMPO",
    description: "Tempo.co - Berita Hukum, KPK & Pengadilan Tipikor",
  },
  {
    id: "tempo-bisnis",
    name: "Tempo.co",
    domain: "tempo.co",
    url: "https://rss.tempo.co/bisnis",
    category: "Ekonomi & Kebijakan",
    color: "#8a0000",
    badge: "TEMPO",
    description: "Tempo.co - Berita Bisnis, Anggaran & Keuangan Negara",
  },
  {
    id: "detik-news",
    name: "Detikcom",
    domain: "detik.com",
    url: "https://news.detik.com/rss",
    category: "Nasional",
    color: "#03396c",
    badge: "DETIK",
    description: "Detikcom - Berita Terhangat Politik & Nasional",
  },
  {
    id: "detik-finance",
    name: "Detikcom",
    domain: "detik.com",
    url: "https://finance.detik.com/rss",
    category: "Ekonomi & Kebijakan",
    color: "#03396c",
    badge: "DETIK",
    description: "Detikcom Finance - Finansial, Properti & Energi",
  },
  {
    id: "republika-nasional",
    name: "Republika",
    domain: "republika.co.id",
    url: "https://www.republika.co.id/rss/nasional",
    category: "Nasional",
    color: "#b22222",
    badge: "REPUBLIKA",
    description: "Republika - Kabar Nasional & Kebijakan Publik",
  },
  {
    id: "republika-hukum",
    name: "Republika",
    domain: "republika.co.id",
    url: "https://www.republika.co.id/rss/hukum",
    category: "Hukum & Korupsi",
    color: "#b22222",
    badge: "REPUBLIKA",
    description: "Republika - Isu Penegakan Hukum & Peradilan",
  },
];
